CREATE USER 'util1'@'%' IDENTIFIED BY '1234';
CREATE USER 'util2'@'%' IDENTIFIED BY '4567';
CREATE USER 'util3'@'%' IDENTIFIED BY '8910';


GRANT ALL PRIVILEGES ON hotel1.* TO 'util1'@'%' IDENTIFIED BY '1234';

GRANT SELECT ON hotel1.* TO util2 IDENTIFIED BY '4567';

GRANT SELECT ON hotel1.station TO util3 IDENTIFIED BY '8910';






